
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - batch.strng.solutions
  resources:
  - daemonjobsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.strng.solutions
  resources:
  - daemonjobsets/finalizers
  verbs:
  - update
- apiGroups:
  - batch.strng.solutions
  resources:
  - daemonjobsets/status
  verbs:
  - get
  - patch
  - update
